"""Training utilities for preparing datasets and fitting FenceNet models."""

from .checkpoints import build_training_checkpoint, save_training_checkpoint
from .data import (
    ACTION_CLASSES,
    ClipLabelRecord,
    PreparedDataset,
    dataset_metadata_rows,
    infer_action_label_from_path,
    infer_subject_id_from_path,
    load_prepared_dataset,
    normalize_action_label,
    normalize_skeleton_sequence,
    parse_clip_labels_csv,
    prepare_ffd_dataset,
    prepare_labeled_video_dataset,
    save_prepared_dataset,
    split_dataset_indices,
    write_clip_label_template,
)
from .trainer import (
    PreparedSkeletonTorchDataset,
    TrainingConfig,
    build_dataloaders,
    build_model,
    evaluate_model,
    skeleton_batch_to_model_input,
    train_model,
)

__all__ = [
    "ACTION_CLASSES",
    "ClipLabelRecord",
    "PreparedDataset",
    "PreparedSkeletonTorchDataset",
    "TrainingConfig",
    "build_dataloaders",
    "build_model",
    "build_training_checkpoint",
    "dataset_metadata_rows",
    "evaluate_model",
    "infer_action_label_from_path",
    "infer_subject_id_from_path",
    "load_prepared_dataset",
    "normalize_action_label",
    "normalize_skeleton_sequence",
    "parse_clip_labels_csv",
    "prepare_ffd_dataset",
    "prepare_labeled_video_dataset",
    "save_prepared_dataset",
    "save_training_checkpoint",
    "skeleton_batch_to_model_input",
    "split_dataset_indices",
    "train_model",
    "write_clip_label_template",
]
